# https://docs.astral.sh/ruff/tutorial/#configuration
# https://docs.astral.sh/ruff/settings/
# Set the maximum line length to 79.
line-length = 79

[lint]
extend-select = ["E501"]
select = [
        "ARG", # flake8-unused-arguments
        "B", # flake8-bugbear
        "C",
        "COM", # flake8-commas
        "DJ", # flake8-django
        "E", # pycodestyle
        "F", # Pyflakes
        "I", # isort
        "PL", # pylint
        "PT", # flake8-pytest-style
        "TID", # flake8-tidy-imports
        "UP", # pyupgrade
        "W",
        "B9"
    ]
ignore = ["E203", "E501", "DJ001", "W191"]

[lint.isort]
known-first-party = ["{{ cookiecutter.project_slug }}"]
known-third-party = [
    "django",
    "django_filters",
    "model_utils",
    {%- if cookiecutter.use_phone_numbers_field == "y" %}
    "phonenumber_field",
    {%- endif %}
    {%- if cookiecutter.use_drf == "y" %}
    "rest_framework",
    {%- endif %}
    "simple_history",
    {%- if cookiecutter.has_blog == "y" or cookiecutter.has_tags == "y" %}
    "taggit",
    "tinymce",
    {%- endif %}
]

[format]
quote-style = "double"
indent-style = "space"

[lint.mccabe]   # DO NOT INCREASE THIS VALUE
max-complexity = 18  # default: 10

[lint.pylint]
max-args = 10
