[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_description }}"
authors = ["{{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
django = "^6.0.5"
django-filter = "^25.1"
pillow = "^11.2.1"
django-allauth = "^65.8.0"
django-bootstrap-datepicker-plus = "^5.0.5"
django-environ = "^0.12.0"
django-model-utils = "^5.0.0"
{%- if cookiecutter.has_blog == "y" or cookiecutter.has_tags == 'y' %}
django-taggit = "^6.1.0"
django-tinymce = "^4.1.0"
{% endif %}
{%- if cookiecutter.use_drf == "y" %}
django-cors-headers = "^4.7.0"
djangorestframework = "^3.16.0"
drf-spectacular = "^0.27.2"
drf-spectacular-sidecar = "^2024.5.1"
{%- endif %}
django-extensions = "^3.2.3"
{%- if cookiecutter.use_phone_numbers_field == 'y' %}
django-phonenumber-field = {version = "^8.0.0", extras = ["phonenumberslite"]}
{%- endif %}
django-simple-history = "^3.8.0"
django-widget-tweaks = "^1.5.0"
gunicorn = "^23.0.0"
psycopg2-binary = "^2.9.10"
ipython = "^9.0.2"
django-bootstrap4 = "^24.3"
ruff = "^0.15.16"

{%- if cookiecutter.use_martor_editor == 'y' %}
martor = "^1.6.45"
{%- endif %}


[tool.poetry.group.test.dependencies]
pytest = "^9.0.3"
pytest-django = "^4.9.0"
factory-boy = "^3.3.1"
pytest-cov = "^6.0.0"
coverage = {extras = ["toml"], version = "^7.0.0"}


[tool.poetry.group.dev.dependencies]
pre-commit = "^4.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
