[project]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_description }}"
authors = [
  { name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}" },
]
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
  "django>=6.1,<6.2",
  "django-filter>=25.2,<27.0",
  "pillow>=12.2.0,<13.0.0",
  "django-allauth>=65.15.1,<66.0.0",
  "django-bootstrap-datepicker-plus>=6.0.0,<7.0.0",
  "django-environ>=0.13,<0.15",
  "django-model-utils>=5.0.0,<6.0.0",
{% if cookiecutter.mail_service == "Amazon SES" %}
  "django-anymail[amazon-ses]>=15.1,<16.0",
{% elif cookiecutter.mail_service != "Other SMTP" %}
  "django-anymail>=15.1,<16.0",
{% endif %}
{% if cookiecutter.has_blog == "y" or cookiecutter.has_tags == 'y' %}
  "django-taggit>=6.1.0,<7.0.0",
  "django-tinymce>=4.1.0,<5.0.0",
{% endif %}
{% if cookiecutter.use_drf == "y" %}
  "django-cors-headers>=4.9.0,<5.0.0",
  "djangorestframework>=3.17.1,<4.0.0",
  "drf-spectacular>=0.29,<0.31",
  "drf-spectacular-sidecar>=2026.3.1,<2027.0.0",
{% endif %}
  "django-extensions>=4.1,<5.0",
{% if cookiecutter.use_phone_numbers_field == 'y' %}
  "django-phonenumber-field[phonenumberslite]>=8.3.0,<9.0.0",
{% endif %}
  "django-simple-history>=3.11.0,<4.0.0",
  "django-widget-tweaks>=1.5.1,<2.0.0",
  "gunicorn>=25.2,<27.0",
  "psycopg2-binary>=2.9.10,<3.0.0",
  "ipython>=9.11.0,<10.0.0",
  "django-bootstrap4>=26.1,<27.0",
{% if cookiecutter.use_martor_editor == 'y' %}
  "martor>=1.6.45,<2.0.0",
{% endif %}
]

[dependency-groups]
test = [
  "pytest>=9.1.1,<10.0.0",
  "pytest-django>=4.12.0,<5.0.0",
  "factory-boy>=3.3.3,<4.0.0",
  "pytest-cov>=7.1,<8.0",
  "coverage[toml]>=7.0.0,<8.0.0",
]
dev = [
  { include-group = "test" },
  "pre-commit>=4.6.2,<5.0.0",
  "ruff>=0.16.4,<0.17.0",
]

[tool.uv]
package = false

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "{{ cookiecutter.project_slug }}.conf.settings.test"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "--reuse-db"
