"""
Django settings for {{ cookiecutter.project_slug }} project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from collections.abc import Callable

import environ
from django.conf import global_settings
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

from ...constants.deployment import (
    ENVIRONMENT_PRODUCTION,
    ENVIRONMENT_STAGING,
    KNOWN_ENVIRONMENTS,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Callable = environ.Path(__file__) - 4
# app directory path override
APPS_DIR = os.path.join(BASE_DIR, "{{ cookiecutter.project_slug }}/apps/")
sys.path.insert(0, APPS_DIR)

# env file injection
env_file = os.path.join(BASE_DIR, ".env")
env = environ.Env()
env.read_env(env_file)

ENVIRONMENT = env.str("ENVIRONMENT", default="local").lower()
IS_PRODUCTION = ENVIRONMENT == ENVIRONMENT_PRODUCTION
IS_STAGING = ENVIRONMENT == ENVIRONMENT_STAGING
IS_LOCAL = ENVIRONMENT not in KNOWN_ENVIRONMENTS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)
if DEBUG and IS_PRODUCTION:
    raise ImproperlyConfigured("Debugging enabled in Production!")

ALLOWED_HOSTS = []


# CORS settingss
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=["http://*.127.0.0.1"],
)
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://*.127.0.0.1",
    ],
)
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)


# Application definition

# Application definition
DJANGO_APPS = [
    # custom admin theme
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.postgres",
]

# 3rd party libraries
THIRD_PARTY_APPS = [
    "allauth",
    "allauth.account",
    "bootstrap4",
    "bootstrap_datepicker_plus",
    "django_extensions",
    "django_filters",
    {%- if cookiecutter.use_phone_numbers_field == 'y' %}
    "phonenumber_field",
    {%- endif %}
    {%- if cookiecutter.use_martor_editor == 'y' %}
    "martor",
    {%- endif %}
    {%- if cookiecutter.use_drf == "y" %}
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    {%- endif %}
    "simple_history",
    {%- if cookiecutter.has_blog == "y" or cookiecutter.use_taggit == 'y' %}
    "tinymce",
    "taggit",
    {%- endif %}
    "widget_tweaks",
]

LOCAL_APPS = [
    "{{ cookiecutter.project_slug }}.apps.dashboard.apps.DashboardConfig",
    "{{ cookiecutter.project_slug }}.apps.login.apps.LoginConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    {%- if cookiecutter.use_drf == "y" %}
    "corsheaders.middleware.CorsMiddleware",
    {%- endif %}
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "{{ cookiecutter.project_slug }}.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.context_processors.sidebar_context"
            ],
        },
    },
]

WSGI_APPLICATION = "{{ cookiecutter.project_slug }}.wsgi.application"
SITE_ID = 1

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Authentication settings
AUTH_USER_MODEL = "login.UserAccount"

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_UNIQUE_EMAIL = True

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard:home_page"
LOGOUT_URL = "logout"
LOGOUT_REDIRECT_URL = "login"

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGES = global_settings.LANGUAGES + [("en-us", "American English")]

TIME_ZONE = "{{ cookiecutter.timezone }}"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MESSAGE_TAGS = {
    messages.DEBUG: "info",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SHELL_PLUS = "ipython"

{%- if cookiecutter.use_phone_numbers_field == "y" %}
# Phone number validator
PHONENUMBER_DEFAULT_REGION = "KE"
{%- endif %}

{%- if cookiecutter.use_drf == "y" %}
# REST framework configuration
DEFAULT_RENDERER_CLASSES = ("rest_framework.renderers.JSONRenderer",)

if DEBUG:
    DEFAULT_RENDERER_CLASSES = DEFAULT_RENDERER_CLASSES + (
        "rest_framework.renderers.BrowsableAPIRenderer",
    )


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": DEFAULT_RENDERER_CLASSES,
    "DEFAULT_PAGINATION_CLASS": "{{cookiecutter.project_slug}}.common.pagination.ResultsPagination",
    "DEFAULT_VERSIONING_CLASS": "{{cookiecutter.project_slug}}.common.versioning.{{ cookiecutter.class_name_prefix }}URLPathVersioning",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "generic_high": "1000/day",
        "generic_low": "20/day",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "{{ cookiecutter.project_name }} API",
    "DESCRIPTION": "{{ cookiecutter.project_name }} API documentation",
    "VERSION": "{{ cookiecutter.version }}",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}
{%- endif %}

{%- if cookiecutter.use_martor_editor == 'y' %}
# martor settings (markdown editor)
MARTOR_THEME = "bootstrap"
{%- endif %}

# Email settings
DEFAULT_EMAIL_DOMAIN = env("DEFAULT_EMAIL_DOMAIN", default="@{{ cookiecutter.project_slug }}.com")
SUPPORT_FROM_NAME = env("SUPPORT_FROM_NAME", default="{{ cookiecutter.project_name }} Support")
SUPPORT_FROM_EMAIL_NAME = env("SUPPORT_FROM_EMAIL_NAME", default="support")
SUPPORT_REPLY_TO_EMAIL_NAME = env("SUPPORT_REPLY_TO_EMAIL_NAME", default="support")

DEFAULT_FROM_EMAIL = SUPPORT_FROM_EMAIL_NAME + DEFAULT_EMAIL_DOMAIN
CONTACT_EMAIL_RECIPIENTS = env.list(
    "CONTACT_EMAIL_RECIPIENTS", default=[SUPPORT_REPLY_TO_EMAIL_NAME]
)

USE_SMTP = env.bool("USE_SMTP", default=False)

if IS_LOCAL:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

if USE_SMTP:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env.str("EMAIL_HOST", default="smtp.sendgrid.net")
    EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="apikey")
    EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
    EMAIL_PORT = env.int("EMAIL_PORT", default=587)
    EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

BOOTSTRAP4 = {
    "include_jquery": True,
}

FRONTEND_HOST = env.str("FRONTEND_HOST", default="http://localhost:8000")

{%- if cookiecutter.has_blog == 'y' %}
TAGGIT_CASE_INSENSITIVE = True
# TinyMCE WYSIWYG Editor configuration
TINYMCE_DEFAULT_CONFIG = {
    "height": 500,
    "width": "100%",
    "menubar": "file edit view insert format tools table help",
    "plugins": """
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen
        insertdatetime media table paste code help wordcount
    """,
    "toolbar": """
        undo redo | formatselect | bold italic backcolor | alignleft aligncenter
        alignright alignjustify | bullist numlist outdent indent | removeformat | help
    """,
    "image_advtab": True,  # Enables advanced image tab options
    "images_upload_url": "/dashboard/tinymce/upload/",  # URL for image uploads
    "automatic_uploads": False,
    "relative_urls": False,
    "remove_script_host": False,
    "file_picker_callback": "django_tinymce_file_picker",
}
{%- endif %}
