"""
Django settings for projectBaseline project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from collections.abc import Callable

import environ
from django.conf import global_settings
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured

from ...constants.deployment import (
    ENVIRONMENT_PRODUCTION,
    ENVIRONMENT_STAGING,
    KNOWN_ENVIRONMENTS,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR: Callable = environ.Path(__file__) - 4
# app directory path override
APPS_DIR = os.path.join(BASE_DIR, "projectBaseline/apps/")
sys.path.insert(0, APPS_DIR)

# env file injection
env_file = os.path.join(BASE_DIR, ".env")
env = environ.Env()
env.read_env(env_file)

ENVIRONMENT = env.str("ENVIRONMENT", default="local").lower()
IS_PRODUCTION = ENVIRONMENT == ENVIRONMENT_PRODUCTION
IS_STAGING = ENVIRONMENT == ENVIRONMENT_STAGING
IS_LOCAL = ENVIRONMENT not in KNOWN_ENVIRONMENTS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)
if DEBUG and IS_PRODUCTION:
    raise ImproperlyConfigured("Debugging enabled in Production!")

ALLOWED_HOSTS = []


# CORS settingss
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=["http://*.127.0.0.1"],
)
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "http://*.127.0.0.1",
    ],
)
CORS_ALLOW_CREDENTIALS = env.bool("CORS_ALLOW_CREDENTIALS", default=True)


# Application definition

# Application definition
DJANGO_APPS = [
    # custom admin theme
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.postgres",
]

# 3rd party libraries
THIRD_PARTY_APPS = [
    "corsheaders",
    "django_extensions",
    "django_filters",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "phonenumber_field",
    "martor",
    "rest_framework",
    "simple_history",
]

LOCAL_APPS = [
    "projectBaseline.apps.login.apps.LoginConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "projectBaseline.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "projectBaseline/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "projectBaseline.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTH_USER_MODEL = "login.UserAccount"

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGES = global_settings.LANGUAGES + [("en-us", "American English")]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static"

MEDIA_URL = "media/"
MEDIA_ROOT = "media"

MESSAGE_TAGS = {
    messages.DEBUG: "info",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "error",
}

# Phone number validator
PHONENUMBER_DEFAULT_REGION = "KE"
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
SHELL_PLUS = "ipython"

# REST framework configuration
DEFAULT_RENDERER_CLASSES = ("rest_framework.renderers.JSONRenderer",)

if DEBUG:
    DEFAULT_RENDERER_CLASSES = DEFAULT_RENDERER_CLASSES + (
        "rest_framework.renderers.BrowsableAPIRenderer",
    )


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": DEFAULT_RENDERER_CLASSES,
    "DEFAULT_PAGINATION_CLASS": "bridge_lab.common.pagination.ResultsPagination",
    "DEFAULT_VERSIONING_CLASS": "bridge_lab.common.versioning.BridgelabURLPathVersioning",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "generic_high": "1000/day",
        "generic_low": "20/day",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Innovatike Inc API",
    "DESCRIPTION": "Innovatike Inc API documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# martor settings (markdown editor)
MARTOR_THEME = "bootstrap"
